version: '3.8'
services:
  db:
    container_name: chatr-db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5435:5432'
    env_file:
      - .env.db
    networks:
      - chatr_network
    volumes:
      - chatr-db:/var/lib/postgresql/data

  redis:
    container_name: chatr-redis
    image: redis
    ports:
      - '6379:6379'
    networks:
      - chatr_network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - chatr-redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  backend:
    container_name: chatr-backend
    image: chatr-backend:latest
    build: ../backend
    ports:
      - '3001:3000'
    env_file:
      - .env.backend
    networks:
      - chatr_network
    depends_on:
      - db
      - redis

  frontend:
    container_name: chatr-frontend
    image: chatr-frontend:latest
    build: ../frontend
    ports:
      - '8081:8080'
    env_file:
      - .env.frontend
    networks:
      - chatr_network
    depends_on:
      - backend

networks:
  chatr_network:
    name: chatr_network

volumes:
  chatr-db:
    driver: local
  chatr-redis:
