version: '3.8'
services:
  frontend:
    container_name: speakr-frontend
    image: speakr-frontend:latest
    build: ../frontend
    ports:
      - '8081:8080'
    env_file:
      - .env.frontend

  backend:
    container_name: speakr-backend
    image: speakr-backend:latest
    build: ../backend
    ports:
      - '3001:3000'
    env_file:
      - .env.backend

  db:
    container_name: speakr-db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.db

    ports:
      - '5435:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
